In [18]:
import numpy as np
from tabulate import tabulate


ModuleNotFoundError: No module named 'tabulate'

In [3]:
prueba = np.linspace(0,0, 10, dtype="int8")
prueba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [5]:
arr = np.linspace(1, 10, 10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
# Lista booleana
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
indices = arr > 5
indices

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
arr[indices]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
arr[arr<5]

array([1, 2, 3, 4], dtype=int8)

In [12]:
arr[(arr > 3) & (arr<10)]

array([4, 5, 6, 7, 8, 9], dtype=int8)

In [14]:
arr[arr>4]=99
arr

array([ 1,  2,  3,  4, 99, 99, 99, 99, 99, 99], dtype=int8)

In [15]:
arr[arr==99]

array([99, 99, 99, 99, 99, 99], dtype=int8)

In [17]:
periodos = float(input('escribe los periodos: '))
presente = float(input('valor presente: '))
interes = presente*(float(input('tasa de interes: ')/100))
cuota = float(input("valor de la cuota: "))

n = np.linspace(0, periodos, periodos)
saldo_ini = np.linspace(0,0, periodos)
saldo_ini[0] = presente
inte = np.linspace(0,0, periodos)
inte[:] = interes
pago = np.linspace(0,0, periodos)
pago[:] = cuota
saldo_final = np.linspace(0, periodos, periodos)

tabla = {
    'Meses': n,
    'Saldo inicial': presente,
    'Interes': inte,
    'Cuota': pago,
    'Saldo final': saldo_final
}

tabulate(tabla, headers='keys', tablefmt='fancy_grid')

ValueError: could not convert string to float: ''