In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
pedazo = arr[0:6]
pedazo

array([0, 1, 2, 3, 4, 5])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
pedazo[:] = 0
pedazo

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [10]:
arr_copy = arr.copy()

In [12]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])