In [1]:
import numpy as np

In [3]:
# ndim me ayuda a determinar el numero de dimensiones que tiene el array, en este caso no tiene ninguna porque es un scalar
scalar = np.array(2018)
print(scalar)
scalar.ndim

2018


0

In [4]:
# Ahora el caso del vector que debe tener 1 una dimension
vector = np.array([1, 2, 3, 4, 5])
print(vector)
vector.ndim

[1 2 3 4 5]


1

In [5]:
# Para el caso de una matriz que tiene 2 dimensiones, en código lo hago con dos listas
matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(matriz)
matriz.ndim
# Puedo agrupar datos

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [6]:
# Sigue teniendo 2 dimensones porque lo agrupe
matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(matriz)
matriz.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


2

In [7]:
# Voy subiendo las dimensiones
tensor = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[9, 10, 11, 12],[13, 14, 15, 16]]])
print(tensor)
tensor.ndim

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


3

Agregar o eliminar dimensiones

In [8]:
# Sin importar la esturctura agrega las dimensiones 
vector = np.array([1, 2, 3, 4, 5], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]


10

In [9]:
# Expansión de dimensiones
expand = np.expand_dims([1, 2, 3, 4], axis=0)
print(expand)
expand.ndim

[[1 2 3 4]]


2

In [19]:
# Eliminar dimensiones
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2)
vector_2.ndim

[[[[[[[[[[1 2 3 4 5]]]]]]]]]] 10
[1 2 3 4 5]


1

In [22]:
# Mi ejemplo de eliminar o agregar dimensiones, con un tensor de 5 dimensiones
tensor = np.array([[[[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]],[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]]]]])
print(tensor, tensor.ndim)
tensor_2 = np.squeeze(tensor)
print('')
print(tensor_2, tensor_2.ndim)
tensor_3 = np.expand_dims(tensor_2, axis=1)
print('')
print(tensor_3, tensor_3.ndim)


[[[[[1 2 3 4 5]
    [5 4 3 2 1]]

   [[1 2 3 4 5]
    [5 4 3 2 1]]]]] 5

[[[1 2 3 4 5]
  [5 4 3 2 1]]

 [[1 2 3 4 5]
  [5 4 3 2 1]]] 3

[[[[1 2 3 4 5]
   [5 4 3 2 1]]]


 [[[1 2 3 4 5]
   [5 4 3 2 1]]]] 4
