In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 20, 10)
arr

array([ 8,  1, 15,  7, 16, 10,  3, 17,  3,  2])

In [4]:
matriz = np.reshape(arr, (2,5))
matriz

array([[ 8,  1, 15,  7, 16],
       [10,  3, 17,  3,  2]])

In [5]:
arr.max()

17

In [6]:
matriz.max()

17

In [7]:
matriz.max(0)

array([10,  3, 17,  7, 16])

In [8]:
matriz

array([[ 8,  1, 15,  7, 16],
       [10,  3, 17,  3,  2]])

In [9]:
matriz.max(1)

array([16, 17])

In [11]:
arr.argmax()

7

In [12]:
matriz.argmax()

7

In [13]:
matriz.argmax(0)

array([1, 1, 1, 0, 0])

In [14]:
matriz.argmax(1)

array([4, 2])

In [15]:
matriz.min()

1

In [16]:
matriz.argmin(1)

array([1, 4])

In [17]:
matriz.ptp()

16

In [18]:
matriz.ptp(1)

array([15, 15])

In [19]:
matriz.ptp(0)

array([ 2,  2,  2,  4, 14])

In [20]:
np.percentile(matriz, 50)

7.5

In [21]:
np.sort(matriz)

array([[ 1,  7,  8, 15, 16],
       [ 2,  3,  3, 10, 17]])

In [22]:
np.median(matriz)

7.5

In [23]:
np.median(matriz, 1)

array([8., 3.])

In [24]:
np.std(matriz)

5.775811631277461

In [25]:
np.var(matriz)

33.36