In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista

Llevarlo a numpy

In [4]:
arr = np.array(lista)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Sumar dimensones

In [6]:
matriz = [[1, 2, 3,], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing

In [9]:
# me va a trear el valor según el numero que le ponga, que se vuelve operable. Empeiza e 0
arr[0]
arr[0] + arr[5]

7

In [10]:
matriz[0]

array([1, 2, 3])

In [11]:
# Puedo ingresar a una posicion dentro de la lista
matriz[0,1]

2

Slicing

In [12]:
arr[0:3]

array([1, 2, 3])

In [15]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [17]:
# los pasos en 3 en 3
arr[::3]

array([ 1,  4,  7, 10])

In [14]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# el valor del final
arr[-1]

10

In [20]:
matriz[1:, 0:1]

array([[4],
       [7]])