In [6]:
import numpy as np


In [2]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [3]:
lista * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [8]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = arr.copy()

In [10]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr / 20

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45])

In [13]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# se puede usar con cualquier operación matemática
arr ** arr2

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [16]:
# Como se ve esto con una matriz
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz2 = matriz.copy()

In [18]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
matriz ** matriz2

array([[        1,         1,         4,        27,       256],
       [     3125,     46656,    823543,  16777216, 387420489]])

In [22]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [23]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [24]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2