In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1, 100, (4, 4))
arr.shape

(4, 4)

In [5]:
arr

array([[56,  4, 38, 33],
       [26, 85, 12, 86],
       [87, 99, 59, 99],
       [27, 71, 86, 52]])

In [6]:
arr.reshape(1, 16)

array([[56,  4, 38, 33, 26, 85, 12, 86, 87, 99, 59, 99, 27, 71, 86, 52]])

In [7]:
arr.reshape(2, 8)

array([[56,  4, 38, 33, 26, 85, 12, 86],
       [87, 99, 59, 99, 27, 71, 86, 52]])

In [8]:
np.reshape(arr, (4,4), "C")

array([[56,  4, 38, 33],
       [26, 85, 12, 86],
       [87, 99, 59, 99],
       [27, 71, 86, 52]])

In [12]:
np.reshape(arr, (2, 8), "F")

array([[56, 87,  4, 99, 38, 59, 33, 99],
       [26, 27, 85, 71, 12, 86, 86, 52]])

In [13]:
np.reshape(arr, (2,8), 'C')

array([[56,  4, 38, 33, 26, 85, 12, 86],
       [87, 99, 59, 99, 27, 71, 86, 52]])

In [14]:
np.reshape(arr, (4,4), "F")

array([[56,  4, 38, 33],
       [26, 85, 12, 86],
       [87, 99, 59, 99],
       [27, 71, 86, 52]])

In [15]:
np.reshape(arr, (1,16),"A")

array([[56,  4, 38, 33, 26, 85, 12, 86, 87, 99, 59, 99, 27, 71, 86, 52]])

In [16]:
np.reshape(arr, (1,16), "C")

array([[56,  4, 38, 33, 26, 85, 12, 86, 87, 99, 59, 99, 27, 71, 86, 52]])

In [18]:
np.reshape(arr, (1, 16), "F")

array([[56, 26, 87, 27,  4, 85, 99, 71, 38, 12, 59, 86, 33, 86, 99, 52]])

In [20]:
tensor = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(tensor, tensor.ndim)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]] 3


In [21]:
tensor.shape

(2, 4, 5)

In [23]:
tensor_2 = np.reshape(tensor, (1,4,10), "C")
print(tensor_2)

[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]
  [ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]]


In [24]:
tensor_2.shape

(1, 4, 10)

In [26]:
tesnor_3 = np.reshape(tensor_2, (2,4,5), "A")
print(tesnor_3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [27]:
tensor_error = np.reshape(tensor, (5,10), "F")

ValueError: cannot reshape array of size 40 into shape (5,10)