In [2]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
#Saber el tipo de dato
arr.dtype

dtype('int64')

En redes neuronales se requeiren de float o numeros con decimanles, se entienden mucho mejor con las maquinas

In [3]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [4]:
# En este caso el output tendrá puntos decimaes
arr

array([1., 2., 3., 4.])

In [6]:
# Defini el tipo de datos desde numply, en este caso lo cambié a booleano y siempre que hay un 0 es Falso
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S21')

In [8]:
# No lo puedo hacer con texto
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4, 5], dtype=int8)

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.double)
arr

array([0., 1., 2., 3., 4., 5.])

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.csingle)
arr

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j], dtype=complex64)

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr = arr.astype(np.longlong)
arr

array([0, 1, 2, 3, 4, 5], dtype=int64)