In [1]:
import pandas as pd
import numpy as np

In [5]:
tech_port = pd.read_csv('/Users/juanmanrique/Documents/numpy_pandas/proyecto/NASA_TechPort.csv', header=0, sep=',')

In [6]:
tech_port.head()

TechPort ID                                      Project Title  \
0       117325  Development of Improved Combustor Scaling Laws...   
1       117098         Quesst Community Test Planning & Execution   
2        94884               NASA Platform for Autonomous Systems   
3        32946                  Autonomous Systems and Operations   
4        14560  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project Description  \
0  To improve current engine (1X) performance and...   
1  Plan and execute sonic boom tests with the X-5...   
2  Autonomous operations are critical for the suc...   
3  The AES Autonomous Systems and Operations (ASO...   
4  The OCULLAR activity pairs a miniature and rug...   

                            Responsible NASA Program  \
0                              Advanced Air Vehicles   
1                              Advanced Air Vehicles   
2                               Mars Campaign Office   
3                               Mars Campaign Office   
4  Center Independent Research & Development: GSF...   

                                    Primary Taxonomy    Project Last Updated  \
0                         TX01.3.6 - Ramjet/Scramjet  12/04/2023 09:47:04 PM   
1                           TX15.1.4 - Aeroacoustics  12/04/2023 09:34:30 PM   
2               TX10.3.3 - Goal and Task Negotiation  11/29/2023 07:12:16 PM   
3  TX10.2.2 - Activity and Resource Planning and ...  11/20/2023 07:07:58 PM   
4              TX08.1.1 - Detectors and Focal Planes  11/17/2023 03:57:25 PM   

                                         Project URL  \
0  Development of Improved Combustor Scaling Laws...   
1  Quesst Community Test Planning & Execution (ht...   
2  NASA Platform for Autonomous Systems (https://...   
3  Autonomous Systems and Operations (https://tec...   
4  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project API URL  
0  https://techport.nasa.gov/api/projects/117325  
1  https://techport.nasa.gov/api/projects/117098  
2   https://techport.nasa.gov/api/projects/94884  
3   https://techport.nasa.gov/api/projects/32946  
4   https://techport.nasa.gov/api/projects/14560

In [7]:
tech_port.tail()

TechPort ID                                      Project Title  \
15837         7402                     Microwave Rain Gauge, Phase II   
15838         7418  A Reusable and Autonomous Ocean-Atmosphere Sen...   
15839        13959  Thin Mirror Shaping Technology for High-Throug...   
15840         7616  Bit Transparent Ternary SERDES for Intra-Syste...   
15841        94322  Development of a Hard X-ray Photoelectric Pola...   

                                     Project Description  \
15837                                                NaN   
15838  The need to acquire observations on oceanic an...   
15839  This proposal is submitted to the NASA Researc...   
15840                                                NaN   
15841  We propose the optimization of the Time Projec...   

                                Responsible NASA Program  \
15837  Small Business Innovation Research/Small Busin...   
15838  Small Business Innovation Research/Small Busin...   
15839                 Astrophysics Research and Analysis   
15840  Small Business Innovation Research/Small Busin...   
15841                 Astrophysics Research and Analysis   

                                        Primary Taxonomy  \
15837  TX06.3.5 - Food Production, Processing, and Pr...   
15838                          TX11.4.8 - Edge Computing   
15839                          TX08.2.1 - Mirror Systems   
15840  TX06.3.5 - Food Production, Processing, and Pr...   
15841                          TX08.2.1 - Mirror Systems   

         Project Last Updated  \
15837  10/10/2018 11:15:04 PM   
15838  10/10/2018 11:15:04 PM   
15839  10/10/2018 11:15:04 PM   
15840  10/10/2018 11:15:04 PM   
15841  10/10/2018 11:15:04 PM   

                                             Project URL  \
15837  Microwave Rain Gauge, Phase II (https://techpo...   
15838  A Reusable and Autonomous Ocean-Atmosphere Sen...   
15839  Thin Mirror Shaping Technology for High-Throug...   
15840  Bit Transparent Ternary SERDES for Intra-Syste...   
15841  Development of a Hard X-ray Photoelectric Pola...   

                                    Project API URL  
15837   https://techport.nasa.gov/api/projects/7402  
15838   https://techport.nasa.gov/api/projects/7418  
15839  https://techport.nasa.gov/api/projects/13959  
15840   https://techport.nasa.gov/api/projects/7616  
15841  https://techport.nasa.gov/api/projects/94322

In [8]:
tech_port.astype(np.bool_)

TechPort ID  Project Title  Project Description  \
0             True           True                 True   
1             True           True                 True   
2             True           True                 True   
3             True           True                 True   
4             True           True                 True   
...            ...            ...                  ...   
15837         True           True                 True   
15838         True           True                 True   
15839         True           True                 True   
15840         True           True                 True   
15841         True           True                 True   

       Responsible NASA Program  Primary Taxonomy  Project Last Updated  \
0                          True              True                  True   
1                          True              True                  True   
2                          True              True                  True   
3                          True              True                  True   
4                          True              True                  True   
...                         ...               ...                   ...   
15837                      True              True                  True   
15838                      True              True                  True   
15839                      True              True                  True   
15840                      True              True                  True   
15841                      True              True                  True   

       Project URL  Project API URL  
0             True             True  
1             True             True  
2             True             True  
3             True             True  
4             True             True  
...            ...              ...  
15837         True             True  
15838         True             True  
15839         True             True  
15840         True             True  
15841         True             True  

[15842 rows x 8 columns]

In [9]:
tech_port.dtypes

TechPort ID                  int64
Project Title               object
Project Description         object
Responsible NASA Program    object
Primary Taxonomy            object
Project Last Updated        object
Project URL                 object
Project API URL             object
dtype: object

In [10]:
tech_port.head()

TechPort ID                                      Project Title  \
0       117325  Development of Improved Combustor Scaling Laws...   
1       117098         Quesst Community Test Planning & Execution   
2        94884               NASA Platform for Autonomous Systems   
3        32946                  Autonomous Systems and Operations   
4        14560  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project Description  \
0  To improve current engine (1X) performance and...   
1  Plan and execute sonic boom tests with the X-5...   
2  Autonomous operations are critical for the suc...   
3  The AES Autonomous Systems and Operations (ASO...   
4  The OCULLAR activity pairs a miniature and rug...   

                            Responsible NASA Program  \
0                              Advanced Air Vehicles   
1                              Advanced Air Vehicles   
2                               Mars Campaign Office   
3                               Mars Campaign Office   
4  Center Independent Research & Development: GSF...   

                                    Primary Taxonomy    Project Last Updated  \
0                         TX01.3.6 - Ramjet/Scramjet  12/04/2023 09:47:04 PM   
1                           TX15.1.4 - Aeroacoustics  12/04/2023 09:34:30 PM   
2               TX10.3.3 - Goal and Task Negotiation  11/29/2023 07:12:16 PM   
3  TX10.2.2 - Activity and Resource Planning and ...  11/20/2023 07:07:58 PM   
4              TX08.1.1 - Detectors and Focal Planes  11/17/2023 03:57:25 PM   

                                         Project URL  \
0  Development of Improved Combustor Scaling Laws...   
1  Quesst Community Test Planning & Execution (ht...   
2  NASA Platform for Autonomous Systems (https://...   
3  Autonomous Systems and Operations (https://tec...   
4  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project API URL  
0  https://techport.nasa.gov/api/projects/117325  
1  https://techport.nasa.gov/api/projects/117098  
2   https://techport.nasa.gov/api/projects/94884  
3   https://techport.nasa.gov/api/projects/32946  
4   https://techport.nasa.gov/api/projects/14560

In [85]:
id = []
id.append(tech_port['TechPort ID'])

In [86]:
id

[0        117325
 1        117098
 2         94884
 3         32946
 4         14560
           ...  
 15837      7402
 15838      7418
 15839     13959
 15840      7616
 15841     94322
 Name: TechPort ID, Length: 15842, dtype: int64]

In [34]:
arr = np.array(id)
arr

array([[117325, 117098,  94884, ...,  13959,   7616,  94322]])

In [38]:
arr.shape

(1, 15842)

In [41]:
arr.reshape(2, 7921)

array([[117325, 117098,  94884, ..., 103153,  93430,   9119],
       [  9312,   9374,   9578, ...,  13959,   7616,  94322]])

In [42]:
arr

array([[117325, 117098,  94884, ...,  13959,   7616,  94322]])

In [43]:
np.reshape(arr, (2,7921), 'C')

array([[117325, 117098,  94884, ..., 103153,  93430,   9119],
       [  9312,   9374,   9578, ...,  13959,   7616,  94322]])

In [44]:
np.reshape(arr, (2,7921), 'A')

array([[117325, 117098,  94884, ..., 103153,  93430,   9119],
       [  9312,   9374,   9578, ...,  13959,   7616,  94322]])

In [45]:
np.reshape(arr, (2,7921), 'F')

array([[117325,  94884,  14560, ...,   7800,   7418,   7616],
       [117098,  32946,  11812, ...,   7402,  13959,  94322]])

In [47]:
np.reshape(arr, (1, 15842), 'F')

array([[117325, 117098,  94884, ...,  13959,   7616,  94322]])

In [48]:
np.reshape(arr, (1, 15842), 'C')

array([[117325, 117098,  94884, ...,  13959,   7616,  94322]])

In [49]:
arr.ndim

2

In [50]:
arr

array([[117325, 117098,  94884, ...,  13959,   7616,  94322]])

In [51]:
arr.max()

146628

In [54]:
other = np.random.randint(1, 1500000, (1, 2,7921))
other

array([[[ 204638,   95813, 1215371, ..., 1027443,  128276, 1063702],
        [ 113504, 1235879,  953511, ...,  929108,  734242, 1104125]]])

In [55]:
other.shape

(1, 2, 7921)

In [56]:
other.ndim

3

In [57]:
arr.reshape(2,1,7921)

array([[[117325, 117098,  94884, ..., 103153,  93430,   9119]],

       [[  9312,   9374,   9578, ...,  13959,   7616,  94322]]])

In [58]:
arr.ndim

2

In [59]:
tech_port.head()

TechPort ID                                      Project Title  \
0       117325  Development of Improved Combustor Scaling Laws...   
1       117098         Quesst Community Test Planning & Execution   
2        94884               NASA Platform for Autonomous Systems   
3        32946                  Autonomous Systems and Operations   
4        14560  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project Description  \
0  To improve current engine (1X) performance and...   
1  Plan and execute sonic boom tests with the X-5...   
2  Autonomous operations are critical for the suc...   
3  The AES Autonomous Systems and Operations (ASO...   
4  The OCULLAR activity pairs a miniature and rug...   

                            Responsible NASA Program  \
0                              Advanced Air Vehicles   
1                              Advanced Air Vehicles   
2                               Mars Campaign Office   
3                               Mars Campaign Office   
4  Center Independent Research & Development: GSF...   

                                    Primary Taxonomy    Project Last Updated  \
0                         TX01.3.6 - Ramjet/Scramjet  12/04/2023 09:47:04 PM   
1                           TX15.1.4 - Aeroacoustics  12/04/2023 09:34:30 PM   
2               TX10.3.3 - Goal and Task Negotiation  11/29/2023 07:12:16 PM   
3  TX10.2.2 - Activity and Resource Planning and ...  11/20/2023 07:07:58 PM   
4              TX08.1.1 - Detectors and Focal Planes  11/17/2023 03:57:25 PM   

                                         Project URL  \
0  Development of Improved Combustor Scaling Laws...   
1  Quesst Community Test Planning & Execution (ht...   
2  NASA Platform for Autonomous Systems (https://...   
3  Autonomous Systems and Operations (https://tec...   
4  Ocean Color Underwater Low Light Advanced Radi...   

                                 Project API URL  
0  https://techport.nasa.gov/api/projects/117325  
1  https://techport.nasa.gov/api/projects/117098  
2   https://techport.nasa.gov/api/projects/94884  
3   https://techport.nasa.gov/api/projects/32946  
4   https://techport.nasa.gov/api/projects/14560

In [65]:
serie = pd.Series(id)
serie

0    0        117325
1        117098
2         9488...
dtype: object

In [66]:
example = pd.Series(['NASA', 'SpaceX', 'Blue Origin', 'Virgin Galactic'], index=[1, 2, 3, 4,])
example

1               NASA
2             SpaceX
3        Blue Origin
4    Virgin Galactic
dtype: object

In [75]:
tech_port['TechPort ID']

0        117325
1        117098
2         94884
3         32946
4         14560
          ...  
15837      7402
15838      7418
15839     13959
15840      7616
15841     94322
Name: TechPort ID, Length: 15842, dtype: int64

In [74]:
tech_port['Project Title']

0        Development of Improved Combustor Scaling Laws...
1               Quesst Community Test Planning & Execution
2                     NASA Platform for Autonomous Systems
3                        Autonomous Systems and Operations
4        Ocean Color Underwater Low Light Advanced Radi...
                               ...                        
15837                       Microwave Rain Gauge, Phase II
15838    A Reusable and Autonomous Ocean-Atmosphere Sen...
15839    Thin Mirror Shaping Technology for High-Throug...
15840    Bit Transparent Ternary SERDES for Intra-Syste...
15841    Development of a Hard X-ray Photoelectric Pola...
Name: Project Title, Length: 15842, dtype: object

In [88]:
info = []
info.append(tech_port['Project Title'])
info

[0        Development of Improved Combustor Scaling Laws...
 1               Quesst Community Test Planning & Execution
 2                     NASA Platform for Autonomous Systems
 3                        Autonomous Systems and Operations
 4        Ocean Color Underwater Low Light Advanced Radi...
                                ...                        
 15837                       Microwave Rain Gauge, Phase II
 15838    A Reusable and Autonomous Ocean-Atmosphere Sen...
 15839    Thin Mirror Shaping Technology for High-Throug...
 15840    Bit Transparent Ternary SERDES for Intra-Syste...
 15841    Development of a Hard X-ray Photoelectric Pola...
 Name: Project Title, Length: 15842, dtype: object]

In [90]:
program = []
program.append(tech_port['Responsible NASA Program'])
program

[0                                    Advanced Air Vehicles
 1                                    Advanced Air Vehicles
 2                                     Mars Campaign Office
 3                                     Mars Campaign Office
 4        Center Independent Research & Development: GSF...
                                ...                        
 15837    Small Business Innovation Research/Small Busin...
 15838    Small Business Innovation Research/Small Busin...
 15839                   Astrophysics Research and Analysis
 15840    Small Business Innovation Research/Small Busin...
 15841                   Astrophysics Research and Analysis
 Name: Responsible NASA Program, Length: 15842, dtype: object]

In [91]:
dict = {info : program for (info, program) in zip(info, program)}
dict

TypeError: unhashable type: 'Series'